---

- name: Connect
  hosts: Agents
  user: admin
  become: true
  

  tasks:

  - name: Update packages
    package:
      name: "*"
      state: latest
      force_apt_get: true

  # - name: Get gnupg
  #   package:
  #     name: gnupg
  #     state: present
      
  - name: Add repo
    shell: |
     echo "deb http://repo.r1soft.com/apt stable main" >> /etc/apt/sources.list
     wget http://repo.r1soft.com/r1soft.asc
     apt-key add r1soft.asc 
     apt-get update
     apt-get install serverbackup-enterprise-agent -y
     
     

  - name: Update packages
    package:
      name: "*"
      state: latest
      force_apt_get: true
  

  - name: Install server-agent
    package:
      name: serverbackup-enterprise-agent
      state: present

  - name: Restart sbm-agent server
    systemd:
     name: sbm-agent
     state: restarted



  - name: Get key
    command: r1soft-setup --get-key http://18.118.160.63:8080